version: '3'

services:
  Db:
    image: postgres
    ports:
      - '5432:5432'
    container_name: Leaguestore
    restart: always
    volumes:
      - store-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Riven231
      POSTGRES_DB: Leaguestore

volumes:
  store-disk: